### ISSUE TITLE
Compiling for python

### ISSUE THREAD

**Issue by silvadirceu** [kisasexypantera94/hpfw#1]
Hi @kisasexypantera94 ,
I'm trying to compile your code for python, but after using cmake instructions in Readme, I can't find pyhpfw.
The compilation of hpfw was ok.

Can you tell me how to compile for python?
I use a virtual env with pyenv.

**Comment by kisasexypantera94** [comment]
Hi, never thought someone would compile this code 😛 
Have you tried doing
```
cmake --build build --target pyhpfw
cd modules/python/
pip install .
```
?

Also try this repo https://github.com/k806house/sber-hp, it is the same project but with some fixes.
You may comment everything related to MKL
```
...


        # MKL RELATED
        # pthread
        # mkl_intel_lp64
        # mkl_sequential
        # mkl_core
        # m
        # dl
)
target_compile_definitions(
        hpfw
        INTERFACE

        -DUSE_FFTW
        # -DEIGEN_USE_MKL_ALL
)
```

If it doesn't work out for you I'll try to see what can be done at the weekend.

**Comment by silvadirceu** [comment]
Hi @kisasexypantera94 ,
thanks for your help.
Why the surprise? You have done a great work. 

As I am using macbook and oneAPI, I had to change the CMakeList.txt to compile hpfw.
Following your instructions, pyhpfw was compiled too.
For python I had to change the path to libpyhpfw.dylib. Do you know any way to set this path automatically? Maybe put it inside the site-package in python env .

One doubt: 
auto index_files = hpfw::utils::get_dir_files(index_dir);
auto search_files = hpfw::utils::get_dir_files(search_dir);

Are Index_files and search_files reference and unknown songs respectively?
These files are audio files or hashes?


CMakeLIsts.txt

target_include_directories(
        hpfw
        INTERFACE
        SYSTEM

        include/

        /usr/local/include
        # /opt/intel/compilers_and_libraries_2020.0.166/mac/mkl/include
        /opt/intel/oneapi/mkl/2021.4.0/include
        /usr/local/Cellar/fmt/8.0.1/include
        /usr/local/include/taglib

        thirdparty/cpp-taskflow-2.2.0
        thirdparty/annoy-1.16.3/src
)
target_link_libraries(
        hpfw
        INTERFACE

        Eigen3::Eigen
        fftw3
        tbb
        essentia
        tag
        avcodec
        avdevice
        avfilter
        avformat
        avresample
        avutil
        chromaprint
        samplerate
        yaml

        /usr/local/Cellar/fmt/8.0.1/lib/libfmt.a

        # MKL RELATED
        pthread
        m
        dl
        /opt/intel/oneapi/mkl/2021.4.0/lib/libmkl_intel_lp64.a
        /opt/intel/oneapi/mkl/2021.4.0/lib/libmkl_sequential.a
        /opt/intel/oneapi/mkl/2021.4.0/lib/libmkl_core.a
        /opt/intel/oneapi/mkl/2021.4.0/lib/libmkl_blacs_mpich_lp64.a
        /opt/intel/oneapi/mkl/2021.4.0/lib/libmkl_scalapack_ilp64.a


)
